CREATE table clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  second_name VARCHAR (50) DEFAULT NULL,
  first_name VARCHAR (50) DEFAULT NULL,
  patronymic VARCHAR (50) DEFAULT NULL,
  phone_number VARCHAR (12) DEFAULT NULL
);

CREATE table mechanics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  second_name VARCHAR (50) DEFAULT NULL,
  first_name VARCHAR (50) DEFAULT NULL,
  patronymic VARCHAR (50) DEFAULT NULL,
  rate DECIMAL(5,2) DEFAULT NULL
);

CREATE table orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  detail VARCHAR (5000) DEFAULT NULL,
  client_id BIGINT DEFAULT NULL,
  mechanic_id BIGINT DEFAULT NULL,
  create_date TIMESTAMP DEFAULT NULL,
  finish_date TIMESTAMP DEFAULT NULL,
  price DECIMAL (10,2) DEFAULT NULL,
  status VARCHAR (15) DEFAULT NULL,
  FOREIGN KEY (client_id) REFERENCES clients(id),
  FOREIGN KEY (mechanic_id) REFERENCES mechanics(id)
);

CREATE VIEW orders_with_fio AS
SELECT orders.id, orders.detail, orders.client_id, orders.mechanic_id,
		orders.status, orders.create_date, orders.finish_date, orders.price,
	CONCAT(clients.second_name, ' ', clients.first_name, ' ', clients.patronymic) AS client_fio,
	CONCAT(mechanics.second_name, ' ', mechanics.first_name, ' ', mechanics.patronymic) AS mechanic_fio
FROM orders
LEFT JOIN clients ON orders.client_id = client.id
LEFT JOIN mechanics ON orders.mechanic_id = mechanic.id;

CREATE VIEW MECHANICS_STATISTIC
AS SELECT
    M.ID,CONCAT(M.SECOND_NAME,' ',M.FIRST_NAME,' ',M.PATRONYMIC)AS MECHANIC_FIO,
    M.RATE,M.FIRST_NAME,M.SECOND_NAME,M.PATRONYMIC,COUNT(O.ID)AS ORDERS_NEW,
    COUNT(O2.ID)AS ORDERS_CONFIRM,COUNT(O3.ID)AS ORDERS_FINISH
FROM MECHANICS M
  LEFT JOIN ORDERS O ON(O.MECHANIC_ID=M.ID AND O.STATUS='Запланирован')
  LEFT JOIN ORDERS O2 ON(O2.MECHANIC_ID=M.ID AND O2.STATUS='Подтвержден')
  LEFT JOIN ORDERS O3 ON(O3.MECHANIC_ID=M.ID AND O3.STATUS='Выполнел')
GROUP BY ID,MECHANIC_FIO,RATE,FIRST_NAME,SECOND_NAME,PATRONYMIC

INSERT INTO CLIENTS(id, second_name, first_name, patronymic, phone_number)
VALUES(3,'Иванов','Иван','Иванович','');
INSERT INTO CLIENTS(id, second_name, first_name, patronymic, phone_number)
VALUES(4,'Храпов','Денис','Олегович','+79713562541');
INSERT INTO CLIENTS(id, second_name, first_name, patronymic, phone_number)
VALUES(12,'Анисимова','Марина','Геннадьевна','+79214578753');
INSERT INTO CLIENTS(id, second_name, first_name, patronymic, phone_number)
VALUES(13,'Петрова','Дарья','Михайловна','');
INSERT INTO CLIENTS(id, second_name, first_name, patronymic, phone_number)
VALUES(18,'Кан','Шао','Петрович','+78003000600');

INSERT INTO MECHANICS(id, second_name, first_name, patronymic, rate)
VALUES(3,'Герасимов','Андрей','Васильевич',100.00);
INSERT INTO MECHANICS(id, second_name, first_name, patronymic, rate)
VALUES(4,'Максимов','Антон','Юрьевич',150.00);
INSERT INTO MECHANICS(id, second_name, first_name, patronymic, rate)
VALUES(5,'Марусин','Иван','Валерьевич',200.00);
INSERT INTO MECHANICS(id, second_name, first_name, patronymic, rate)
VALUES(6,'Фамилиев','Имен','Отчествович',120.00);

INSERT INTO ORDERS(id, detail, client_id, mechanic_id, create_date, finish_date, price, status)
VALUES(2,'Замена масла ДВС',4,6,'2019-03-01 00:00:00.000000','2019-03-21 00:00:00.000000',3000.00,'Выполнен');
INSERT INTO ORDERS(id, detail, client_id, mechanic_id, create_date, finish_date, price, status)
VALUES(3,'ТО-1',13,4,'2019-03-12 00:00:00.000000','2019-03-12 00:00:00.000000',1500.00,'Выполнен');
INSERT INTO ORDERS(id, detail, client_id, mechanic_id, create_date, finish_date, price, status)
VALUES(4,'Заправка кондиционера',18,4,'2019-03-15 00:00:00.000000','2019-03-16 00:00:00.000000',1500.00,'Подтвержден');
INSERT INTO ORDERS(id, detail, client_id, mechanic_id, create_date, finish_date, price, status)
VALUES(5,'Техническая мойка',3,3,'2019-03-22 00:00:00.000000','2019-03-22 00:00:00.000000',150.00,'Запланирован');

SHUTDOWN;